markdown: redcarpet
pygments: true

redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

title: Pauline Te
description: Pauline Te
disqus_shortname: jayce85
# Your site's domain goes here. Leave localhost server or blank when working locally.
url: http://www.pauline-te.com

# Owner/author information
owner:
    name: Pauline Te
    avatar: avatar.jpg
    bio: 
    # Social networking links used in footer. Update and remove as you like.
    twitter:
    facebook: pauline.te
    github:
    stackexchange:
    linkedin:
    instagram:
    flickr:
    tumblr:
    # For Google Authorship https://plus.google.com/authorship
    google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-49885519-1
google_analytics_domain: pauline-te.com
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# permalink: pretty
permalink: /:year/:month/:day/:title/

# Amount of post to show on home page
paginate: 3

exclude: ["bower.json", "package.json", "README.md", "gulpfile.js", "build.sh", "assets", "node_modules"]
